### ISSUE TITLE
Does not compile with Cpp 11.2.0

### ISSUE THREAD

**Issue by free-creations** [free-creations/a_j_midi#4]
Attempt to compile with newer version of gcc brings several errors like the following:

```
alsa_receiver_queue.cpp:253:21: error: ‘sleep_for’ is not a member of ‘std::this_thread’
```
